apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: credit-platform
type: Opaque
stringData:
  DEVISE_JWT_SECRET_KEY: "ed2e9831ba8f6ed9157acd0804e6ebfb0f472cd797cdf0632baf6752c66029e1af16567bdb66ea4bf3b01bcc5ea0e2f26e349a5ea3ecb9ed6e14af2ffb86f84d"
  CREDIT_API_DATABASE_PASSWORD: "securepassword"
  SIDEKIQ_USERNAME: "angel"
  SIDEKIQ_PASSWORD: "123456"

